# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Pull Request Verification

on:
  push:
    branches: [ latest ]
  pull_request:
    branches: [ latest ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - run: node --version
    - run: npm --version

    - name: Install pnpm
      run: npm i -g pnpm

    - name: Install npm dependencies
      run: pnpm install

    - name: Lint the code
      run: pnpm run lint

    - name: Build browser distribution
      run: pnpm run build --if-present

    - name: Run tests
      run: pnpm run test:ci
      env:
        CI: true

    - name: Run coverage
      run: pnpm run test:coverage:ci
      env:
        CI: true

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
